titzer/virgil

- aeneas/src/x86/X86Assembler.v3
- bin/dev/virgil-vim/syntax/virgil.vim
- test/x86/asm/X86AssemblerTestGen.v3
Adds missing SSE instructions and tests for the X86 assembler. I've tried to keep to idiomatic virgil as much as possible.
> Add missing SSE instructions to X86 assembler

- test/check-bootstrap.bash
- test/common.bash
- test/compare.bash
- test/diagnose.bash
Adds two scripts:
1. `test/check-bootstrap.bash`: runs two different versions of Aeneas and outputs the ten smallest binaries which have differences (for ease of debugging).
2. `test/compare.bash`: runs two different versions of Aeneas on a particular test case and outputs the diff of the SSA, instructions, and binary. To be used in conjunction with the above.
~Kunal
> Add scripts to check differences in bootstrapped binary

- aeneas/src/x86/X86Assembler.v3
- test/x86/asm/X86AssemblerTestGen.v3
Refactors the comparison instructions to reduce repeated code. Code is more in-line with `cmov()` now. Also updates the move instructions to reflect the actual operands they can take.
> Refactor SSE instructions

- aeneas/src/arm/ArmRegSet.v3
- aeneas/src/mach/MachBackend.v3
- aeneas/src/mach/RegAlloc.v3
- aeneas/src/x86/X86CodeGen.v3
- aeneas/src/x86/X86RegSet.v3
This adds register classes which can be used to discriminate against floating-point or integer registers. Have to workaround the unstable move insertion order introduced by the hashing function.
Future PRs build on the above in order to add SSE support.
~Kunal
> Add register classes

- aeneas/src/main/Version.v3
- aeneas/src/x86/X86Assembler.v3
- test/x86/asm/X86AssemblerTestGen.v3
Adds `movd r/m32, xmm` instruction. This will be used to implement the `int.view(float)` functionality.
~Kunal
> Add move from xmm to r/m32

- aeneas/src/main/Version.v3
- aeneas/src/x86/X86Assembler.v3
- aeneas/src/x86/X86MacroAssembler.v3
- test/x86/asm/X86AssemblerTestGen.v3
This is a fairly big patch. I've tried to make each commit small-ish so that reviewing it is more digestible. The meat of the patch is the implementation of conversion and truncation between floats and (unsigned) ints. 
A few things to note:
- The conversion and truncation functions added in the MacroAssembler were either implemented in C first and compiled with `icc` using `-msse4.2 -m32 -O3` or they were based on how the JVM implements them.
- The two x87 FPU instructions were what `icc` spat out for the conversion between a `float` and `unsigned int`. The conversion is quite simple to do with these instructions. It's a bit of a nightmare in just SSE instructions (although technically, the `fisttp` instruction was added in SSE3).
- I was not so sure how to respect calling convention …
> Improve support for SSE instruction generation

- aeneas/src/arm/ArmRegSet.v3
- aeneas/src/mach/MachBackend.v3
- aeneas/src/mach/MachLowering.v3
- aeneas/src/mach/MoveResolver.v3
- aeneas/src/mach/RegAlloc.v3
- aeneas/src/main/Version.v3
- aeneas/src/x86/X86Assembler.v3
- aeneas/src/x86/X86CodeGen.v3
- aeneas/src/x86/X86MacroAssembler.v3
- aeneas/src/x86/X86RegSet.v3
- aeneas/test/MoveResolverTest.v3
- test/float/ret_tuple03.v3
- test/float/ret_tuple04.v3
This patch basically condenses every change *except* the actual isel for floating point support on x86. Unfortunately, I looked into it and the x87 FPU dependencies will be necessary until we move to x64.
I've heavily commented the stubs and macros in the X86MacroAssembler to make it clear what every function does. I'll create a new PR for the isel when this one is approved.
~Kunal
> Improve floating point support for x86 target

- aeneas/src/arm/ArmRuntime.v3
- aeneas/src/mach/MachBackend.v3
- aeneas/src/x86-64/X86_64Backend.v3
- aeneas/src/x86/X86Backend.v3
- aeneas/src/x86/X86CodeGen.v3
- aeneas/src/x86/X86MacroAssembler.v3
Quick change that I noticed. Makes it so that 64-bit only uses one spill slot. Does make assumptions that at least 32-bit word size.
> Add check for word size when calculating number of spill slots

- README.md
The _Harmonizing Classes, Functions, Tuples, and Type Parameters in Virgil III_ paper is a great in-depth overview of Virgil's features but the link at the bottom of the README is hidden behind a paywall (this link isn't).
> [doc] README: add link to paper

- rt/wave/wave.node.js
`wave.node.js` does not return an exit code causing `aeneas test` to fail at test `test/system/exit_main0.v3`:
```
(/tmp/srackham/virgil-test/aeneas/bootstrap/x86-linux/Aeneas) system
Running       int           | 35 of 35 passed
Running       int-ra        | 35 of 35 passed
Compiling     jar           | 35 of 35 passed
Running       jar           | 35 of 35 passed
Compiling     wave          | 35 of 35 passed
Running       wave@node     |
exit_main0.v3: fail: /tmp/srackham/virgil-test/system/wave/exit_main0.v3.exit.diff
34 of 35 passed 1 failed
```
> Fix wave.node.js exit code

- aeneas/src/main/Version.v3
- lib/util/Strings.v3
- test/core/parser/str02.v3
- test/core/string12.v3
- test/lib/StringsTest.v3
> [lang] escaped apostrophes in string literals are optional

- .github/workflows/ci.yml
The x86-linux and x86_64-linux CI were accidentally swapped.
> Fix x86 CI

- aeneas/src/main/CLOptions.v3
- aeneas/src/main/Compiler.v3
- aeneas/src/main/Version.v3
- aeneas/src/ssa/SsaContext.v3
- aeneas/src/x86-64/X86_64Backend.v3
To enable globalRegAlloc: use `-global-regalloc` instead of `-opt=+GlobalRegAlloc`
> Add global-regalloc compile option using matcher

- lib/asm/x86-64/X86_64Assembler.v3
- test/asm/x86-64/X86_64AssemblerTestGen.v3
Also added tests to cover previously implemented instructions.
> [x86-64]: Add assembler methods for v128 population count

- lib/asm/x86-64/X86_64Assembler.v3
- test/asm/x86-64/X86_64AssemblerTestGen.v3
- Added a new utility method `emit_rex_bbb_r_r2` to match the encoding of v128 lane extractions.
- Added four new test patterns for the assembler.
> [x86-64]: Add assembler and new utility methods for v128 extract_lane

- lib/x86-64-linux/SyscallLayouts.v3
I think a typo was introduced by doing `s/struct/layout` haha
> Fix typo in comment

- aeneas/src/main/Version.v3
- aeneas/src/v3/V3.v3
To reproduce the bug: `v3c -run -ssa-int -trace test/core/array_tuple21.v3`
> Fix V3.renderBottom

- aeneas/src/ir/Normalization.v3
- aeneas/src/ir/Reachability.v3
- aeneas/src/ir/SsaNormalizer.v3
- aeneas/src/ir/TypeNorm.v3
- aeneas/src/ir/VariantSolver.v3
- aeneas/src/main/CLOptions.v3
- aeneas/src/vst/Verifier.v3
This PR shifts the variant logic into `VariantSolver.v3`, and migrates away from the use of `DataNorm` to `VariantNorm`. `VariantNorm`s are able to represent both enum-like variants (no fields) and single-case, flattened variants.
This does not add any additional functionality.
> Shift DataNorm representation to VariantNorm

- aeneas/src/main/Version.v3
- aeneas/src/vst/Parser.v3
- aeneas/src/vst/Verifier.v3
- aeneas/src/vst/Vst.v3
- aeneas/src/vst/VstPrinter.v3
- test/variants/parser/packing06.v3
- test/variants/parser/packing07.v3
- test/variants/parser/packing08.v3
- test/variants/parser/packing09.v3
- test/variants/parser/packing10.v3
- test/variants/parser/packing11.v3
- test/variants/parser/packing12.v3
- test/variants/parser/packing13.v3
- test/variants/parser/packing14.v3
- test/variants/parser/packing15.v3
- test/variants/parser/packing16.v3
- test/variants/parser/packing17.v3
- test/variants/parser/packing18.v3
- test/variants/parser/packing19.v3
- test/variants/parser/packing20.v3
Introduces `VstPackingDecl` and `VstPackingExpr`, allowing for nested packing expressions and packing literals.
> Packing Declaration Parsing

- aeneas/src/ir/SsaNormalizer.v3
- aeneas/src/ir/VariantSolver.v3
- test/variants/ub_eq08.v3
- test/variants/ub_eq09.v3
- test/variants/ub_eq10.v3
- test/variants/ub_eq11.v3
- test/variants/ub_eq12.v3
- test/variants/ub_eq13.v3
Variant equality is now done on a case-by-case basis. Previously, it did not correctly dispatch the variant equality method.
In the added test case, the old version would merge `B` and `C` together to become `#ref`, and then use `RefEq` instead, which is incorrect.
> [unbox] Fix variant equality to be case-by-case

- aeneas/src/wasm/WasmTarget.v3
Failure on `ub_merge00` and `ub_prim02` tests as compiler was picking a 32-bit scalar to represent a 64-bit field.
> [unbox] Fix Wasm Unboxing Bug

- lib/asm/x86-64/X86_64Assembler.v3
- lib/asm/x86/X86Assembler.v3
This adds support for the lock prefix to be used when writing is `asm`.
> Add support for lock prefix

- lib/asm/x86-64/X86_64Assembler.v3
Adds support for exchange instructions in `x86-64` that can be used  for atomic stores and other purposes.
> Add exchange instructions to x86-64Assembler

- lib/asm/x86-64/X86_64Assembler.v3
- test/asm/x86-64/X86_64AssemblerTestGen.v3
Add `negb_r` `negw_r` `negd_r` `negq_r`  instruction to lib/asm/x86-64
> Add 'negn_r' instruction to lib/asm/x86-64

- aeneas/src/ir/Normalization.v3
- aeneas/src/ir/VariantSolver.v3
- test/variants/ub_rec05.v3
- test/variants/ub_rec06.v3
Fixes two separate bugs with variant unboxing uncovered by the `-unbox-variants` flag:
- Recursive tests are more exhaustive: previously, it would attempt to unbox variants even if cases referred to their sibling types.
- We were saving space by caching the ClassAlloc constructor in `rc.orig.methods[0]`. This is not correct, because multiple `RaClass`es can have the same `rc.orig`.
> Fix bugs with `-unbox-variants`

- lib/util/Stack.v3
This PR adds the capability to push a range of values on to `ArrayStack`, created for resolving [this](https://github.com/titzer/wizard-engine/blob/d989c9038e7357f41bb0fa41d0d944e224ae09bd/src/engine/v3/V3Interpreter.v3#L42) in Wizard.
> Added `pushr` to `ArrayStack`

- lib/util/Ranges.v3
Added various binary search functions from the optimization PR in Wizard to `Ranges.v3`.
TODO: add tests in `RangesTest.v3`
> Added search functions in `Ranges.v3`

- lib/util/Ranges.v3
- test/lib/RangesTest.v3
It seems like `startsWith` and `endsWith` currently exhibits different behaviors in that a range can be a prefix of itself in `startsWith`, but cannot be a suffix of itself in `endsWith`. This PR changes `endsWith` to match with `startsWith`.
> [lib] Fixed assymetry between `Ranges.startsWith` and `Ranges.endsWith`

- lib/util/Map.v3
- test/lib/MapTest.v3
This PR adds support for removing a key-value pair from hash map along with a basic test for `lib/util/Map.v3`.
This would be useful for the Virgil language server that I'm working on, which needs a LRU implementation (with hashmap) and I thought it would be useful to be in the standard util library.
> [lib] Added `HashMap.remove` to `Map.v3`

- lib/util/Sexpr.v3
I don't remember if you thought this should be added to util, but:
```
def parser = SexpParser.new(filename, file_bytes);
def res = parser.readSexp();
match (res) {
Success(res) => {
...
}
err => {
...
}
}
```
> Add s-expression parser to lib/util

- aeneas/src/vst/Parser.v3
- aeneas/src/vst/Vst.v3
- aeneas/src/vst/VstPrinter.v3
- lib/util/List.v3
- test/core/var_rephint.v3
For `var_rephint.v3`, it prints:
```
(BlockStmt
(LocalStmt
("x": int (repHints #somehint #another)
(Literal "12": int)))
(ReturnStmt
(VarExpr[Local] "x": int)))
```
I'm going to make all the printing more structured like so:
```
(BlockStmt
(LocalStmt
("x" (type int) (repHints #somehint #another)
(Literal "12" (type int))))
(ReturnStmt
(VarExpr[Local] "x" (type int))))
```
I'll also fix the nesting issue we saw with MatchStmt
> Var rep hints / VstPrinter update

- aeneas/src/vst/Parser.v3
- test/funexpr/parser/fun_ret_explicit01.v3
- test/funexpr/parser/simple_body13.v3
- test/funexpr/parser/simple_body14.v3
- test/funexpr/parser/simple_body15.v3
- test/funexpr/parser/simple_body16.v3
- test/funexpr/parser/simple_body17.v3
- test/funexpr/parser/simple_body18.v3
- test/funexpr/parser/simple_body19.v3
- test/funexpr/parser/simple_body20.v3
- test/funexpr/parser/simple_body21.v3
- test/funexpr/parser/simple_body22.v3
- test/funexpr/seman/fun_ret_explicit01.v3
- test/funexpr/seman/simple_body16.v3
- test/funexpr/seman/simple_body17.v3
- test/funexpr/seman/simple_body18.v3
- test/funexpr/seman/simple_body19.v3
- test/funexpr/seman/simple_body20.v3
- test/funexpr/seman/simple_body21.v3
- test/funexpr/seman/simple_body22.v3
- test/funexpr/seman/simple_body23.v3
Adds support for explicitly typing the return in simple fn bodies:
```scala
def pop_i32() => stack.pop().unbox_i32();
def pop_i32() -> TypeVar.I32 => stack.pop().unbox_i32();
```
It's a bit ugly but I'd like it for CBD stuff where there are a lot of simple functions where the types can be a bit confusing without annotations.
It can also help when inference is too precise, this is a contrived example but I ran into it before somewhere I can't remember:
```scala
type SomeADT {
case X;
case Y;
}
def foo() => SomeADT.X; // foo inferred as void -> SomeADT.X
// def foo() -> SomeADT => SomeADT.X; // would typecheck properly
def main() {
var a = foo();
System.puts(if(a == SomeADT.X, "x", "y"));
System.ln();
a = SomeADT.Y; // type error
System.puts(if(a == SomeADT.Y, "y", "x"));
System.ln();
}
``` …
> explicit simple fun body ret type
